version: '3.2'
services:
  redis:
    container_name: v-redis
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "6379:6379"
    network_mode: "host"
    restart: always
    command: redis-server --requirepass SOUBAO@99

  rabbitmq:
    container_name: v-rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=soubao
      - RABBITMQ_DEFAULT_PASS=soubao
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "15672:15672"
      - "5672:5672"
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mysql:
    container_name: v-mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: soubao@2015
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3307:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    

 

