DROP DATABASE IF EXISTS bb2_admin;
CREATE DATABASE bb2_admin;
DROP DATABASE IF EXISTS bb2_auth;
CREATE DATABASE bb2_auth;
DROP DATABASE IF EXISTS bb2_mall;
CREATE DATABASE bb2_mall;
DROP DATABASE IF EXISTS bb2_order;
CREATE DATABASE bb2_order;
DROP DATABASE IF EXISTS bb2_seller;
CREATE DATABASE bb2_seller;
DROP DATABASE IF EXISTS bb2_user;
CREATE DATABASE bb2_user;
DROP DATABASE IF EXISTS bb2_seata;
CREATE DATABASE bb2_seata;
DROP DATABASE IF EXISTS bb2_im;
CREATE DATABASE bb2_im;

CREATE USER `bb2_master_user`@`%` IDENTIFIED BY 'soubao@2020';
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_admin`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_auth`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_mall`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_order`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_seller`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_user`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;
flush privileges;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_seata`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;
flush privileges;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, 
CREATE VIEW, DELETE, DROP, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, REFERENCES, SELECT, SHOW VIEW, TRIGGER, 
UPDATE ON `bb2\_im`.* TO `bb2_master_user`@`%` WITH GRANT OPTION;
flush privileges;