version: "3"
services:
  seata-server:
    restart: always
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      # - SEATA_IP=120.24.42.191
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./seata/conf:/root/seata-config